vim.keymap.set("n", "<space>gs", ":Git<CR>")
vim.keymap.set("n", "<space>ga", ":Gwrite<CR>")
vim.keymap.set("n", "<space>gc", ":Git commit<CR>")
vim.keymap.set("n", "<space>gr", ":Git rebase -i<CR>")
vim.keymap.set("n", "<space>gd", ":Git diff<CR>")
vim.keymap.set("n", "<space>gD", ":Gdiffsplit<CR>")
vim.keymap.set("n", "<space>gb", ":Git blame<CR>")
vim.keymap.set("n", "<space>gl", ":Git log<CR>")
vim.keymap.set("n", "<space>gp", ":Git pull<CR>")
vim.keymap.set("n", "<space>gP", ":Git push<CR>")
