return {
	"ellisonleao/gruvbox.nvim",
	"EdenEast/nightfox.nvim",
	"rebelot/kanagawa.nvim",
	"catppuccin/nvim",
	{ "zenbones-theme/zenbones.nvim", dependencies = "rktjmp/lush.nvim" },
	"xero/miasma.nvim",
	"kvrohit/rasmus.nvim",
	"AlexvZyl/nordic.nvim",
	"webhooked/kanso.nvim",
	"bjarneo/ash.nvim",
	"pebeto/dookie.nvim",
	"vague-theme/vague.nvim",
	"jckmgns/curtailed",
	"slugbyte/lackluster.nvim",
	"ptdewey/darkearth-nvim",
	"ishan9299/nvim-solarized-lua",
}
